### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by YTG1234** [Tzabarcord/discord-bot#1]
Custom commands should work in a similar way to [Fabric Bot tags](https://github.com/FabricMC/Community/tree/main/tags) or [K9](https://github.com/tterrag1098/K9) tricks.

## How to add?
Custom commands will be added using pull requests to a new GitHub repository. They will be reviewed by anyone who wants to review them!

## Format
Custom commands will use TOML for text/embed/alias content, and TypeScript or JavaScript for script content. Scripts will work in a similar way to [Linkie](https://github.com/shedaniel/linkie-discord) scripting.

**Comment by YTG1234** [comment]
I've started working on this. Kotlinx Serialization doesn't support TOML so we'll use YAML. (Why not Json? It doesn't support multiline strings)

```yaml
name: customcommand
type: EMBED
embed:
  title: "Hello World"
  description: "This is yes yes yes"
  fields:
    - name: "Field 1"
      content: "UIAUSINSNinwfeiwenfw"
      inline: false
```
